Initial commit of material3 base template
google-developer-training/basic-android-kotlin-compose-training-waterme pull request #3
Opened 2023-03-14 15:44 UTC by johnshea

2023-03-14 21:35 UTC, kkuan2011 requested changes

2023-03-14 21:35 UTC, kkuan2011 commented on README.md
> +Amphibians app
wrong readme file?

2023-03-14 23:33 UTC, johnshea commented on README.md
> +Amphibians app
Agreed - wrong README.md.

2023-03-15 20:35 UTC, kkuan2011 approved these changes

2023-03-15 21:10 UTC, kkuan2011 requested changes
I think we actually need to preserve the blank lines in the license header text, so could you update the license headers? and then I can review again, thanks!

2023-05-04 14:44 UTC, closed without merging